name: Android CI Build

on:
  push:
    branches: [ "master", "main" ]
  pull_request:
    branches: [ "master", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        # ویژگی کش گریدل از اینجا حذف شد تا ارور برطرف شود

    - name: Find Project and Build
      run: |
        GRADLE_PATH=$(find . -name "gradlew" | head -n 1)
        
        if [ -z "$GRADLE_PATH" ]; then
          echo "❌ خطا: فایل gradlew در هیچکدام از پوشه‌های شما پیدا نشد!"
          echo "این یعنی سورس اندروید شما ناقص است یا با نرم‌افزار دیگری ساخته شده است."
          exit 1
        fi
        
        DIR_NAME=$(dirname "$GRADLE_PATH")
        echo "✅ پروژه اندروید در پوشه $DIR_NAME پیدا شد."
        
        cd "$DIR_NAME"
        chmod +x gradlew
        ./gradlew assembleDebug

    - name: Upload All APKs
      uses: actions/upload-artifact@v4
      if: success()
      with:
        name: my-app-apk
        path: '**/*.apk'
